node {    
      def app     
      stage('Clone repository') {               
             
            checkout scm    
      }     
      stage('Build image') {         
       
            app = docker.build("majumder1996/nodejs-demo")    
       }     
      stage('Test image') {           
            app.inside {            
             
             sh 'echo "Tests passed"'        
            }    
        }     
       stage('Push image') {
       docker.withRegistry('https://registry.hub.docker.com', 'dockurhub') {            
       app.push("${env.BUILD_NUMBER}")            
       app.push("v:0.1")        
              }    
           }
        }