node {
    def commit_id
    def docker = "my docker"
    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit_id"
        commit_id = readFile('.git/commit_id').trim()
    }
    stage('test') {
        nodejs(nodeJSInstallationName: 'nodejs') {
            sh 'npm install --only-dev'
            sh 'npm test'
        }
    }
    stage('deploy') {
            nodejs(nodeJSInstallationName: 'nodejs') {
            sh 'npm start'
        }
    }
}
