node {
    def commit_id
    def docker = "my docker"
    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit_id"
        commit_id = readFile('.git/commit_id').trim()
    }
    stage('test') {
        nodejs(nodeJSInstallationName: 'nodejs') {
            sh 'npm install --only-dev'
            sh 'npm test'
        }
    }
    stage('docker build/push') {

        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {            
            app.push("${env.BUILD_NUMBER}")            
            app.push("latest")        
        }
    }
}
